import React, { useState } from 'react';
import {
  Navigation,
  Download,
  Copy,
  Check,
  X,
  Code2
} from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { broadcastMeshEvent } from '../../utils/meshBus';

interface GpxKmlExportModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const GpxKmlExportModal: React.FC<GpxKmlExportModalProps> = ({ isOpen, onClose }) => {
  const { calculatedRoute, hubs, language } = useApp();
  const [format, setFormat] = useState<'gpx' | 'kml' | 'geojson'>('gpx');
  const [copied, setCopied] = useState<boolean>(false);

  if (!isOpen) return null;

  const routeHubs = calculatedRoute
    ? calculatedRoute.pathHubIds.map(id => hubs.find(h => h.id === id)).filter(Boolean)
    : [];

  const generateGpx = (): string => {
    const timestamp = new Date().toISOString();
    return `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="AidRoute Sovereign Logistics Engine" xmlns="http://www.topografix.com/GPX/1/1">
  <metadata>
    <name>AidRoute Humanitarian Convoy Mission</name>
    <desc>Tactical corridor navigation generated by AidRoute</desc>
    <time>${timestamp}</time>
  </metadata>
${routeHubs.map(h => `  <wpt lat="${h!.lat}" lon="${h!.lng}">
    <name>${h!.name.en}</name>
    <desc>${h!.region.toUpperCase()} Hub - Type: ${h!.type}</desc>
    <sym>Flag, Blue</sym>
  </wpt>`).join('\n')}
  <trk>
    <name>Primary Convoy Track</name>
    <trkseg>
${routeHubs.map(h => `      <trkpt lat="${h!.lat}" lon="${h!.lng}">
        <name>${h!.name.en}</name>
      </trkpt>`).join('\n')}
    </trkseg>
  </trk>
</gpx>`;
  };

  const generateKml = (): string => {
    const coords = routeHubs.map(h => `${h!.lng},${h!.lat},0`).join(' ');
    return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>AidRoute Relief Convoy Corridor</name>
    <description>Tactical route with ${calculatedRoute?.totalDistanceKm || 0} km total distance</description>
    <Style id="routeStyle">
      <LineStyle>
        <color>ff00aaff</color>
        <width>4</width>
      </LineStyle>
    </Style>
${routeHubs.map(h => `    <Placemark>
      <name>${h!.name.en}</name>
      <description>Region: ${h!.region}, Capacity: ${h!.warehouseCapacityTons} MT</description>
      <Point>
        <coordinates>${h!.lng},${h!.lat},0</coordinates>
      </Point>
    </Placemark>`).join('\n')}
    <Placemark>
      <name>Convoy Transit Corridor</name>
      <styleUrl>#routeStyle</styleUrl>
      <LineString>
        <extrude>1</extrude>
        <tessellate>1</tessellate>
        <coordinates>${coords}</coordinates>
      </LineString>
    </Placemark>
  </Document>
</kml>`;
  };

  const generateGeoJson = (): string => {
    const geojson = {
      type: "FeatureCollection",
      features: [
        ...routeHubs.map(h => ({
          type: "Feature",
          geometry: {
            type: "Point",
            coordinates: [h!.lng, h!.lat]
          },
          properties: {
            id: h!.id,
            name: h!.name[language],
            type: h!.type,
            region: h!.region,
            warehouseCapacityTons: h!.warehouseCapacityTons
          }
        })),
        {
          type: "Feature",
          geometry: {
            type: "LineString",
            coordinates: routeHubs.map(h => [h!.lng, h!.lat])
          },
          properties: {
            distanceKm: calculatedRoute?.totalDistanceKm || 0,
            transitHours: calculatedRoute?.totalTransitTimeHrs || 0,
            carbonKg: calculatedRoute?.totalCarbonKg || 0
          }
        }
      ]
    };
    return JSON.stringify(geojson, null, 2);
  };

  const payload = format === 'gpx' ? generateGpx() : format === 'kml' ? generateKml() : generateGeoJson();

  const handleCopy = () => {
    navigator.clipboard.writeText(payload);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    broadcastMeshEvent({
      appId: 'aidroute',
      appName: 'AidRoute',
      type: 'nominal',
      message: `Tactical GPS mission coordinates copied: ${routeHubs.length} waypoints (${format.toUpperCase()})`,
      metric: `${format.toUpperCase()}`
    });
  };

  const handleDownload = () => {
    const mime = format === 'geojson' ? 'application/geo+json' : 'application/xml';
    const blob = new Blob([payload], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `aidroute-mission-${Date.now()}.${format}`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
    broadcastMeshEvent({
      appId: 'aidroute',
      appName: 'AidRoute',
      type: 'nominal',
      message: `Tactical mission file downloaded: ${a.download}`,
      metric: `GPS Mission`
    });
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-sm flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 max-w-4xl w-full shadow-2xl space-y-5 animate-in zoom-in-95 duration-200 max-h-[92vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-200 dark:border-slate-800">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-amber-500/10 text-amber-600 dark:text-amber-400 flex items-center justify-center font-bold">
              <Navigation className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-900 dark:text-white flex items-center gap-2">
                <span>Tactical GPS Mission Exporter (GPX / KML / GeoJSON)</span>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-amber-500/10 text-amber-700 dark:text-amber-300 border border-amber-500/20 font-bold">
                  GARMIN & ATAK
                </span>
              </h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Export calculated convoy waypoints and corridor tracks for ruggedized GPS and SCIF tactical displays.
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="btn-press px-3 py-1.5 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-slate-700 dark:text-slate-300 text-xs font-bold flex items-center gap-1.5 hover:bg-slate-100 dark:hover:bg-slate-700"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy'}</span>
            </button>

            <button
              onClick={handleDownload}
              className="btn-press px-3.5 py-1.5 rounded-xl bg-amber-600 hover:bg-amber-700 text-white text-xs font-bold flex items-center gap-1.5 shadow-md shadow-amber-600/20"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download .{format.toUpperCase()}</span>
            </button>

            <button
              onClick={onClose}
              className="p-1.5 rounded-xl text-slate-400 hover:text-slate-600 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-800"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Format Selector & Mission Waypoints */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
          <div>
            <label className="text-[11px] font-bold text-slate-700 dark:text-slate-300 block mb-1">
              Geospatial Standard
            </label>
            <div className="flex rounded-xl bg-slate-100 dark:bg-slate-800 p-1 border border-slate-200 dark:border-slate-700">
              {(['gpx', 'kml', 'geojson'] as const).map(fmt => (
                <button
                  key={fmt}
                  onClick={() => setFormat(fmt)}
                  className={`flex-1 py-1 rounded-lg font-mono font-bold uppercase transition ${
                    format === fmt
                      ? 'bg-white dark:bg-slate-900 text-amber-600 dark:text-amber-400 shadow-sm'
                      : 'text-slate-600 dark:text-slate-400 hover:text-slate-900'
                  }`}
                >
                  {fmt}
                </button>
              ))}
            </div>
          </div>

          <div className="col-span-2 p-2.5 rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 flex items-center justify-between text-xs">
            <div className="flex items-center gap-2">
              <MapPin className="w-4 h-4 text-amber-500" />
              <div>
                <span className="text-[10px] text-slate-500 font-mono block">Active Mission Route</span>
                <span className="font-bold text-slate-900 dark:text-white">
                  {routeHubs.length > 0 ? routeHubs.map(h => h!.name.en).join(' → ') : 'No active route calculated'}
                </span>
              </div>
            </div>
            <div className="text-right font-mono text-[11px]">
              <span className="text-amber-600 font-bold">{calculatedRoute?.totalDistanceKm || 0} km</span>
              <span className="text-slate-400 block">{calculatedRoute?.totalTransitTimeHrs || 0} hrs</span>
            </div>
          </div>
        </div>

        {/* Code Output Viewer */}
        <div className="space-y-1.5">
          <span className="text-[11px] font-mono text-slate-500 dark:text-slate-400 font-bold block flex items-center gap-1.5">
            <Code2 className="w-3.5 h-3.5 text-amber-500" />
            Formatted Geospatial Output ({format.toUpperCase()})
          </span>
          <pre className="p-4 rounded-2xl bg-slate-950 text-amber-300 font-mono text-xs overflow-x-auto max-h-80 border border-slate-800 leading-relaxed shadow-inner">
            <code>{payload}</code>
          </pre>
        </div>
      </div>
    </div>
  );
};
